apiVersion: batch/v1
kind: Job         # We are testing the Job resource type
metadata:
  name: producer-job  # A name must be given to the Job type in the metadata section
spec:                     # This is the specification where we can even put the number of replicas
  template:               # Specified info needed to run the pod and what runs in the pod
    metadata:
      labels:
        app: producer        # some label to give to this pod (see the matching label above)
    spec:                 # actual specification
      containers:
      - name: producer       # this is going to be used for DNS name
        image: 192.168.1.64:5000/iot   # this is the image in registry accessible
                                             # from all our workers
        # volumeMounts:
        # - mountPath: .
        #   name: consumed

        imagePullPolicy: Always  # This forces the node to pull the image
        command: ["python"]
        args: ["producer.py"] 

  #     volumes:
  #     - name: consumed
  #  # mount /data/foo, but only if that directory already exists
  #       hostPath:
  #         path: . # directory location on host
  #         #type: Directory # this field is optional 
        
      restartPolicy: Never